### ISSUE TITLE
Avoid cloning midstep

### ISSUE THREAD

**Issue by Kixunil** [kneasle/sapling#23]
Currently, when editing a node, the code clones the node, edits it mutably and then stores the result. This is slower than an alternative approach: as a collection is being cloned one item at a time, the node to be edited (replaced or deleted) is compared against the item being cloned and if they match, the new one is inserted instead of the old one (or skipped in case of deletion).

I imagine signatures roughly like this:

```rust
fn delete_child(&self, child_index_to_delete: usize) -> Result<Self, Self::Error>;
fn replace_child(&self, child_index_to_replace: usize, new_child: Self::Child) -> Result<Self, Self::Error>;
fn insert_child(&self, index: usize, side: Side, new_child: Self::Child) -> Result<Self, Self::Error>;
```

One interesting property of this is that it also statically guarantees that the editor won't ignore the error and store a malformed node somewhere.

(I wanted to attend the stream but mismanaged my schedule. :( )

**Comment by kneasle** [comment]
I agree that your suggested approach would be faster.  However, for the time being I would rather prioritise code 'intuitiveness' over raw speed - on the basis that Sapling as-of-now is hardly usable it doesn't really matter if we have top-notch performace (yet!).

The static verification of syntax trees would be nice - but is really hard to extend to arbitrary languages (which would be a **really** useful thing for Sapling to be able to do).  Ideally we'd be able to have a system similar to that of [tree-sitter](https://github.com/tree-sitter/tree-sitter), which would allow Sapling to edit languages specified by an arbitrary grammar (probably written in a language like lex/yacc which provides extra information like char mappings, as well as a way to specify arbitrary numbers of children without using left-recursion).  However, I'd love to find a way to get both - but I can't see a way.

I'm not 100% sure what your suggested solution entails, but I'd imagine that every language would be represented as many interconnected `struct`s (like [in rustc](https://github.com/rust-lang/rust/blob/master/compiler/rustc_ast/src/ast.rs)).  The issue I see is that pressing different keys could correspond to generating different concrete types and so it'd be very unclear at what step the typing should be enforced.  We could use `&dyn`, which would also prevent monomorphisation causing huge executable bloat - but I'm too new to Rust to see if/how that'd work.  It would still mean that every language has to be baked into Sapling, which is less than ideal - ideally all languages would be specified in the same way.

**Comment by Kixunil** [comment]
Hmm, the operation I described seemed intuitive enough for me, but maybe I have a mind accomodated to that sort of thinking, :)

>  that every language would be represented as many interconnected structs (like in rustc)

skimmed through rustc code and it looks like what I had in mind as well.

>  The issue I see is that pressing different keys could correspond to generating different concrete types and so it'd be very unclear at what step the typing should be enforced.

I don't think I understand what do you mean, can you give an example?

> We could use `&dyn`, which would also prevent monomorphisation causing huge executable bloat - but I'm too new to Rust to see if/how that'd work. It would still mean that every language has to be baked into Sapling, which is less than ideal - ideally all languages would be specified in the same way.

It should be possible to at least separate them into plugin libraries. It may be still harder to use than having generic tree description but I imagine it could be faster. I happen to have some experience writing plugin code (not in Rust yet, just C++) so maybe I could help here.

Either way, having something like `dyn` on the boundary between the editor and the language will definitely make sense.

**Comment by kneasle** [comment]
> Hmm, the operation I described seemed intuitive enough for me, but maybe I have a mind accomodated to that sort of thinking, :)

Tbh, I don't overly bothered about what the code does - I just think that the current code is much more declarative.

> I don't think I understand what do you mean, can you give an example?

Tbh, I also don't really see what I meant :laughing:.  To be honest, what I was thinking was that `Ast::to_char` would potentially return multiple types, but I see that we could just use `dyn` to do that anyway.

> It should be possible to at least separate them into plugin libraries. It may be still harder to use than having generic tree description but I imagine it could be faster. I happen to have some experience writing plugin code (not in Rust yet, just C++) so maybe I could help here.
> 
> Either way, having something like `dyn` on the boundary between the editor and the language will definitely make sense.

Having the languages be pluginable would be great - it would be a good compromise between having native-level performance and not having to recompile the core of the editor every time the languages change (which I admit probably wouldn't be very often but still).
