### ISSUE TITLE
No stream today (5th December)

### ISSUE THREAD

**Issue by kneasle** [kneasle/sapling#31]
I've just got home from uni, and I can't get my laptop up and running in time.

It will be happening next week - I just can't find a better way to let people know than making github issues 😆.

**Comment by Kixunil** [comment]
Good idea, was waiting at first then thinking to write here. :D

**Comment by stokhos** [comment]
can't wait to run sapling on my pc

**Comment by kneasle** [comment]
> Good idea, was waiting at first then thinking to write here. :D

I'm sort of wondering whether it's worth getting a twitter account for this kind of thing... But I don't think I'd use it very much and anyway I try to avoid as much social media as possible out of principle.

@stokhos: unless you're running Windows, the instructions for using Sapling as it stands are in the [`readme-tlc` branch](https://www.github.com/kneasle/sapling/tree/readme-tlc/README.md), if you want to have a fiddle around! Bug reports/things you find unintuitive are very welcome :grinning:.

**Comment by Kixunil** [comment]
While I do use Twitter, I purposely limit it lately. GitHub is my favorite social netwrok. :)
GitHub issue works better for me personally.

**Comment by kneasle** [comment]
Ah OK... I think I'll use GitHub issues then, at least until I get 1k subs and then I can do community posts instead (1k looks a long way away, though... :laughing:).

Tbh, I also like github more than social media sites like Facebook (at least if you want to get stuff done).

**Comment by stokhos** [comment]
> > Good idea, was waiting at first then thinking to write here. :D
> 
> I'm sort of wondering whether it's worth getting a twitter account for this kind of thing... But I don't think I'd use it very much and anyway I try to avoid as much social media as possible out of principle.
> 
> @stokhos: unless you're running Windows, the instructions for using Sapling as it stands are in the [`readme-tlc` branch](https://www.github.com/kneasle/sapling/tree/readme-tlc/README.md), if you want to have a fiddle around! Bug reports/things you find unintuitive are very welcome :grinning:.

Actually I'm learning rust ,  I'd like to contribute.

**Comment by kneasle** [comment]
> Actually I'm learning rust , I'd like to contribute.

Aha nice! - contributions are very welcome!  I've been creating some new issues with the tag `good-first-issue` which are what they say on the tin.  If anything, they're definitely on the easy side but you're welcome to have a go at one of them if you want - just comment that you want to do it and I'll assign you!
