### ISSUE TITLE
Rename current 'Command' to make way for actual commands

### ISSUE THREAD

**Issue by kneasle** [kneasle/sapling#32]
Currently all the code that refers to a 'command' is actually referring to a normal-mode keystroke command, as opposed to proper commands which start with `:` (like `:quit` in Vim).

I'm not sure what to rename current commands to... `NormalModeCommand` or `KeyStrokeCommand`?  Both feel quite long, so perhaps we could call it something like `KeyCmd`.

We should also probably refactor the whole normal-mode command system into its own module, but that's some refactoring for another day.

This issue is probably quite easy to fix - all the changes are confined to `src/editor.rs`, and it should be a fairly simple refactoring job.  Not the most exciting first issue, but straightforward nonetheless.

**Comment by stokhos** [comment]
I'd like to take this one.

**Comment by kneasle** [comment]
Coool - you're assigned now :grin:! I think these changes will create merge conflicts with #34, so I would either base your new branch on `upstream/edit-method-cleanup` or just wait for #34 to be merged (which would be better since more changes are needed before merging).

I had a quick look at what the code currently looks like, and I reckon the best way to refactor this is to move all the 'normal mode' stuff (i.e. `mod command_log`, `Command`, `KeyMap`, `Action`, `parse_command`) into its own module before doing the refactoring.  Probably the easiest way to do this is to just stick everything into a `mod normal_mode { ... }` block inside `src/editor.rs`, but long-term it would be better turn `src/editor.rs` into a folder.  I think at this point, `Action` doesn't need to be renamed, and `Command` would be better named to `KeyStroke`.

If you fancy some bigger refactoring, then `editor::Editor::consume_command_char` could be moved and renamed to something like `editor::normal_mode::consume_keystroke` (it'd then need extra parameters for the command string and `KeyMap`).

Also, it's conventional to not make PRs from your own master branch - usually people make their own branches with a descriptive name (like `stokhos/refactor-normal-mode`).  It doesn't really matter - it just makes reading incoming PRs a bit easier, as well as allowing you to work on multiple PRs concurrently.  Just a tip :grin:.

Hope I'm not sounding patronising (it's not meant that way).  It's always nice to see new names on PRs!

**Comment by Kixunil** [comment]
`KeyStroke` sounds good to me.

**Comment by kneasle** [comment]
Yeah I also like `KeyStroke` the best - also I don't think it's too bad to have `normal_mode::Action` and `command::Action` since I doubt they'd be used enough to be worth importing directly (most of the specific code should be stored in the editor sub-modules anyway).

**Comment by stokhos** [comment]
Cool. My major is not Computer related. So if anything that I'm doing is not conventional, feel free to let me know.

**Comment by kneasle** [comment]
Ah that's OK!  I wondered if you might be in the US, on the basis that you seem to almost exclusively work on things when I'm asleep :laughing:.

**Comment by stokhos** [comment]
Yes. I'm in USA. What about you.

**Comment by kneasle** [comment]
I'm in England - I'm currently 3rd year studying CS at Oxford :grin:.

**Comment by stokhos** [comment]
I have finished refactoring, but two parts that are not very clear to me.

1.  Move all the 'normal mode' stuff (i.e. `mod command_log`, `Command`, `KeyMap`, `Action`, `parse_command`) into its own module before doing the refactoring into its own module before doing the refactoring. Probably the easiest way to do this is to just stick everything into a `mod normal_mode { ... }` block inside `src/editor.rs
`
There is `default_keymap` function. Do I need to put this inside the `mod normal_mode `?  Currently, I put this function inside `normal_mode`.

2.  If you fancy some bigger refactoring, then `editor::Editor::consume_command_char` could be moved and renamed to something like `editor::normal_mode::consume_keystroke` (it'd then need extra parameters for the command string and `KeyMap`).
`consume_command_char` is a method of `Editor`. How can I put it into `normal_mode` without puting `Editor` into `normal_mode`?

**Comment by kneasle** [comment]
> There is `default_keymap` function. Do I need to put this inside the `mod normal_mode `?  Currently, I put this function inside `normal_mode`.

I'm not really sure what to do with `default_keymap`. It seems to me that it's more to do with configuration than with how normal mode works so once we decide on a way to handle configuration we can move it there.  For the time being, I think having it live inside `editor::normal_mode` makes sense. @Kixunil, what do you reckon? 

I've also been looking into how NeoVim is structured, which might help us with further refactoring...

> 2.  If you fancy some bigger refactoring, then `editor::Editor::consume_command_char` could be moved and renamed to something like `editor::normal_mode::consume_keystroke` (it'd then need extra parameters for the command string and `KeyMap`).
> `consume_command_char` is a method of `Editor`. How can I put it into `normal_mode` without putting `Editor` into `normal_mode`?

Actually having said that, I think that directly moving the function is probably not the best idea - it's still reliant on the fact that `Editor` uses a `String` for the command buffer.  Ideally we'd have some `struct` who's sole purpose is to parse keystrokes and eventually generate an `Action`, but it's quite late here and I'm writing this on my phone so I won't go into more details now.  Also I think that it's better to do refactoring in lots of small PRs instead of one PR - it's just easier to check that the code is in fact equivalent, as well as giving more opportunity for spotting better ways of doing things.

**Comment by Kixunil** [comment]
Yes, it makes sense to me. I guess keymap will be a struct later:

```
struct KeyMap {
    normal_mode: HashMap<char, normal_mode::Command>,
    visual_mode: HashMap<char, visual_mode::Command>,
    // ...
}

impl Default for KeyMap {
   // ...
}

impl KeyMap {
    // perhaps Config = str, we will see in the future
    fn from_config(config: &Config) -> Self {
        //
    }
```

**Comment by kneasle** [comment]
I like the look of having a `KeyMap` struct - it could also handle converting `char`s into `KeyStroke`s and then that would be neatly encapsulated.  But for the time being, we only have normal mode config to deal with, so we may as well wait until we have more keybindings to store - unless anyone wants to do the refactoring now...?

**Comment by Kixunil** [comment]
Exactly, don't bother with the struct until there are more modes.
