### ISSUE TITLE
Allow `h`/`l` to move to previous and next sibling

### ISSUE THREAD

**Issue by kneasle** [kneasle/sapling#33]
This would mean that `h` and `k` both map to `Direction::Prev` while `j` and `l` both map to `Direction::Next`.  This is because the current keybindings are very unintuitive if the sibling nodes are arranged horizontally, as is fairly common (e.g. function parameters).

This would make a good first issue, the only changes required are in `default_keymap` in `src/editor.rs`.  Remember to update the README.

**Comment by stokhos** [comment]
I'd like get started with these one.

**Comment by kneasle** [comment]
Coool - I've assigned you to this! If you need any more pointers then stick them here and I'll be happy to help.

Also one thing I didn't mention is that there are [some unit tests](https://github.com/kneasle/sapling/blob/master/src/editor.rs#L658) at the bottom of `src/editor.rs` for keystroke parsing that a) might break when you add extra keybindings and keys become defined and b) should have the new key bindings added to them.
