### ISSUE TITLE
Remap `d` to `x`

### ISSUE THREAD

**Issue by kneasle** [kneasle/sapling#35]
Since `d` currently deletes the node under the cursor, it would make more sense to be consistent with Vim and map `x` to this instead.

**Comment by kneasle** [comment]
This could probably be easily done in the same PR as #33...

**Comment by stokhos** [comment]
On my pc, when I pressed d, sapling quited. Do you observe same behaviour?

**Comment by kneasle** [comment]
In this situation, I think it's that Sapling currently `panic!`s if you attempt to delete the root of the tree (and since the root is selected by default, this is the immediate behaviour of typing `d`).

This will be fixed once #34 is merged.
