### ISSUE TITLE
Combine Ast::is_insert_char and Ast::is_replace_char

### ISSUE THREAD

**Issue by kneasle** [kneasle/sapling#37]
Both `Ast::is_insert_char` and `Ast::is_replace_char` perform the same purpose of performing tree validation and preventing illegal nodes to be added to the tree.  Therefore, it makes more sense to have one method that also takes an child index, like `Ast::is_valid_child(&self, index: usize, c: char) -> bool`.

In fact, `Ast::is_replace_char` is not correct - for example, a JSON string could be either the key of an object (as in `{"string": true}`) or just as a 1st class JSON datastructure (like `["string"]`).  In the latter, the string may be replaced, but in the former it can't.  We need to know what the parent is (in fact, we only need to know what the parent is if the grammar is context-free).

This shouldn't be too hard; maybe not a first issue but it doesn't require lots of code-base knowledge - the compiler errors and unit tests should provide guidance.

**Comment by stokhos** [comment]
I'd like to fix this one.
But could you be more specific over this. 
To me, it seems I will need to do:
1. I need to add another function to check the validity of the new node.
2. Delete `is_replace_char`
3. Replace `is_replace_char` with `is_insert_char` in `dag.rs`.

**Comment by stokhos** [comment]
```rust
pub trait Ast<'arena>: std::fmt::Debug + Clone + Eq + Default + std::hash::Hash {
  
  fn replace_chars(&self) -> Box<dyn Iterator<Item = char>>;

  fn is_replace_char(&self, c: char) -> bool {
        self.replace_chars().any(|x| x == c)
    }


}
```
```rust
    /// Replaces the current cursor with a node represented by `c`
    fn replace_cursor(&mut self, c: char) -> EditResult {
        self.perform_edit(
            |_this: &mut Self,
             _parent_and_index: Option<(&'arena Node, usize)>,
             cursor: &'arena Node| {
                if !cursor.is_replace_char(c) {
                    return Err(EditErr::CannotBeChild {
                        c,
                        parent_name: _parent_and_index
                            .map_or("<root>".to_string(), |(p, _)| p.display_name()),
                    });
                }

                let new_node = cursor.from_char(c).ok_or(EditErr::CharNotANode(c))?;

                let new_node_name = new_node.display_name();
                Ok((
                    new_node,
                    EditLocation::Cursor,
                    EditSuccess::Replace {
                        c,
                        name: new_node_name,
                    },
                ))
            },
        )
```

I have 2 questions in above codes
1. I have a question regarding `replace_char`. Why the body of this function can be omitted?
2. `cursor`'s type is `Path`, and what it stores are numbers, but  `!cursor.is_replace_char(c)` can detect illegal `char`. Did I miss something over here?

**Comment by stokhos** [comment]
From my understanding, what you want to do is make `replace` to be able to work on key of an object. But I'm not sure how you want this to be implemented.

**Comment by kneasle** [comment]
Oh sorry I didn't realise you were working on this - I mostly stopped open source stuff over Christmas, so didn't get round to replying till now.

>     1. I have a question regarding `replace_char`. Why the body of this function can be omitted?

The body is omitted because `replace_char` and `is_replace_char` are both being defined in the trait `Ast`.  What this is saying is that any type implementing `Ast` **must** provide a definition of `replace_char`, but they may omit the definition of `is_replace_char` (and the general-but-slower implementation from `Ast` will be used).  I think both of these can be replaced.

>     2. `cursor`'s type is `Path`, and what it stores are numbers, but  `!cursor.is_replace_char(char)` can detect illegal `char`. Did I miss something over here?

In this context `cursor` is defined to be a node: `cursor: &'arena Node`, but yeah I guess there's a bit of a naming collision here.

**Comment by stokhos** [comment]
> Oh sorry I didn't realise you were working on this - I mostly stopped open source stuff over Christmas, so didn't get round to replying till now.
> 
> > ```
> > 1. I have a question regarding `replace_char`. Why the body of this function can be omitted?
> > ```
> 
> The body is omitted because `replace_char` and `is_replace_char` are both being defined in the trait `Ast`. What this is saying is that any type implementing `Ast` **must** provide a definition of `replace_char`, but they may omit the definition of `is_replace_char` (and the general-but-slower implementation from `Ast` will be used). I think both of these can be replaced.
> 
> > ```
> > 2. `cursor`'s type is `Path`, and what it stores are numbers, but  `!cursor.is_replace_char(char)` can detect illegal `char`. Did I miss something over here?
> > ```
> 
> In this context `cursor` is defined to be a node: `cursor: &'arena Node`, but yeah I guess there's a bit of a naming collision here.

I figured  that. BTW merry xmax, and happy new year.

I figured out where to get started, but for now, I'm stuck on the implementation.

**Comment by kneasle** [comment]
Here's an example for what I'm trying to do (this turns out to be a fair bit more complicated than I expected):

## Deletion

Deletion doesn't have a node-type parameter, so no changes are required.

## Replacing the cursor

This is where the work needs to happen.

Currently, it is up to the node underneath the cursor to decide whether or not the replace is valid (using `Ast::is_replace_char`).  _Importantly, the node under the cursor has no information about what lies above it in the tree_.

So imagine that we are trying to replace a JSON `"string"` with `true` using `rt`.  The only information `Ast::is_replace_char` is given is that we are replacing a `string` with `true`.  But we have two cases:
- `["string"]` -> `[true]`:  this is OK and implies that `Ast::is_replace_char(JSON::Str("string"), 't')` should return `true`
- `{"string": null}` -> `{true: null}`: this is **not** OK and implies that `Ast::is_replace_char(JSON::Str("string"), 't')` should return `false`

Therefore, `Ast::is_replace_char(JSON::Str("string"), 't')` cannot have a return value, since both `true` and `false` are wrong.

But the **parent** of the cursor does have enough information to tell these two cases apart.  In the first case, the parent is a `JSON::Array`; in the second case, the parent is a `JSON::Field`.  So my proposed solution is to create a new function
```rust
Ast::is_valid_child(
    &self,        // `self` is the **parent** of the node being checked for validity
                  // (in this case, the node under the cursor being replaced)
    index: usize, // `index` says which child of `self` is being checked for validity
    c: char,      // `c` represents the node that we are trying to put as child #`index` of `&self`
) -> bool;
```
which is called on **the parent** of the node being replaced to check for validity.  So for example, in the following cases (where we're replacing `"string"` with `true`):

| example | what we'd call | value returned |
|----|----|----|
|`["string"]` -> `[true]` | `Ast::is_valid_child(&JSON::Array(...), 0, 't')` | `true` |
| `{"string": null}` -> `{true: null}` | `Ast::is_valid_child(&JSON::Field(...), 0, 't')` | `false` |
| `{"key": "string"}` -> `{"key": true}` | `Ast::is_valid_child(&JSON::Field(...), 1, 't')` | `true` |

So in the second and third case, the `index` parameter is used to determine if the replacement is valid.  This will just turn into a big `match` over the possible `JSON` values - most of them won't use the index parameter, but a few might.

Thinking about it more, we need an extra method `Ast::is_valid_root(c: char) -> bool` for the case where the root is being replaced.

## Insertion

For insertion, the code doesn't need to change very much - instead of calling `parent.is_insert_char(c)`, we call `parent.is_valid_child(insert_index, c)`.

Does this explanation make more sense?  It is pretty complicated, but I still think it's an improvement over the current system.

**Comment by stokhos** [comment]
it clear enough for me to continue my work.

**Comment by stokhos** [comment]
Is there a way to insert a `key` for `key-value` pair?

**Comment by kneasle** [comment]
> Is there a way to insert a `key` for `key-value` pair?

Currently, there isn't because key-value pairs **must** have both of their children to exist. So key value pairs (called `JSON::Field`) get implicitly created when inserting into an object.

So inserting `true` into `{}` will create `{"": true}`, which implicitly creates the key/value pair. I'm not sure this is the best thing to do, but it is how Sapling works right now.

**Comment by stokhos** [comment]
I have a question regarding the `closure`, I notice that you used `closure` a lot. Why in certain cases, you preferred `closure` to `function`?

**Comment by kneasle** [comment]
So a closure is like a function, except that it can 'capture' variables from where it's defined.  So let's say we have the following code:

```rust
// Print result calls whatever function or closure you gave it, and prints the answer
fn print_result(mut func: impl Fn() -> usize) {
    println!("{}", func());
}

// A simple function that returns 42
fn answer_to_everything() -> usize {
    42
}

fn main() {
    // Here, this prints 42, because that's what `answer_to_everything` returns
    print_result(answer_to_everything);

    // But we can use a closure to get `print_result` to print the contents of `x`,
    // because `x` is 'captured' by the closure
    let x = 3;
    let closure = || x;
    // Prints 3
    print_result(closure);
}
```

The rust book has [an example](https://doc.rust-lang.org/book/ch13-01-closures.html), which may be more helpful.

Generally, in the code I use 'pure' functions where possible.  But in some cases (like `DAG`'s edit functions), capturing local variables is needed (usually the closures are capturing the variable `c` that specifies what node should be inserted).

Closures are a little complex and fiddly, but at the end of the day they are simply anonymous functions that can access local variables.

**Comment by stokhos** [comment]
Got it.  

I thought it would provide some performance improvement over function .

**Comment by kneasle** [comment]
> I thought it would provide some performance improvement over function .

I'm pretty sure that there's no case where closures perform **better** than straight function calls.  Closures are more powerful/flexible - they can do things that straight functions can't - but a lot of function calls in Rust get 'inlined' which enables **a ton** of optimisation, and I think this is more difficult for closures.
