### ISSUE TITLE
Rename `CursorPath` to simply `Path`

### ISSUE THREAD

**Issue by kneasle** [kneasle/sapling#45]
I think this is fine, despite the potential naming collision with `std::path::Path` on the basis that we are unlikely to use both in the same code.  @Kixunil - thoughts?

This'd be a fairly straightforward refactoring job - there might be some rogue pieces of documentation left to patch up but it should be nice and easy.

**Comment by Kixunil** [comment]
I agree, possibly also rename the module, so that we can write `cursor::Path` in case shit hits the fan.

**Comment by kneasle** [comment]
Oh yeah I forgot to mention the whole reason for doing this, which is that `CursorPath`s are unlikely to only be used to refer to the cursor and is more a generic path down a tree.  `NodePath` feels a bit long and unwieldy for something so fundamental, so I thought we could go with `Path`.

**Comment by stokhos** [comment]
I'd like to work on this one

**Comment by kneasle** [comment]
Cool! You're assigned!
