### ISSUE TITLE
Create a macro for generating TestJSON trees.

### ISSUE THREAD

**Issue by kneasle** [kneasle/sapling#46]
Currently, Sapling has two datatypes for JSON trees (`JSON` is analogous to `&str` whereas `TestJSON` is analogous to `String`).  As the name suggests, `TestJSON` is used primarily for easily creating test cases, but is most of the time more verbose than `JSON` because of its long name.  If we could create a macro for this then it would be very epic.

Something like:
```rust
test_json!([true, false, {"key" => "value"}])
```

should expand to:
```rust
TestJSON::Array(vec![
  TestJSON::True,
  TestJSON::False,
  TestJSON::Object(vec![
    (
      TestJSON::String("key".to_string()),
      TestJSON::String("value.to_string())
    )
  ])
]);
```

anyone who wants to have some fun with macros and knows what they're doing is welcome to do this :grin:.

**Comment by Kixunil** [comment]
I think this can be replaced by converting serde_json value, right?

**Comment by kneasle** [comment]
I think it can - the only issue is that `serde_json::Value` stores objects as an unordered (hash)maps, whereas `TestJson` and `Json` both keep the ordering of the fields.  I think it's fine - I've been refactoring the tests and this hasn't yet been a problem.

I've also got a new record of most compiler errors generated in one go (332 errors and 1 warning) :tada:.  Doing the refactoring is also taking **forever** - I'm down to 145 errors now but I've spent nearly 2 hours and it's now nearly 1am.  I need some sleep.

**Comment by Kixunil** [comment]
https://docs.serde.rs/serde_json/enum.Value.html#variant.Object

> By default the map is backed by a BTreeMap. Enable the preserve_order feature of `serde_json` to use IndexMap instead, which preserves entries in the order they are inserted into the map.

**Comment by kneasle** [comment]
Oooooh!  I got round the issue by forcing the JSON to have the keys in alphabetical order but this is a much better solution :laughing:.
