### ISSUE TITLE
Code reorganisation

### ISSUE THREAD

**Issue by kneasle** [kneasle/sapling#55]
I think that all 'core' datatypes (`editable_tree::{Direction, Side, cursor::Path}`, `ast::size::Size`) should probably live in their own module.  I'm not sure if this is a good/better way to group these datatypes, but I reckon we'll probably need a place for really basic datatypes at some point.

We could re-import them in `main.rs`, so all other modules can import them as simply `crate::Path` or `crate::Size`, but I'm not overall convinced that this is useful, particularly with the easy name collisions with `std::path::Path`.

Once we've moved `editable_tree::cursor::Path`, the whole `editable_tree` module doesn't make any sense.  So I think we should move `editable_tree/mod.rs` to `editor/dag.rs`, so that DAG is now `editor::dag::DAG`.

So pretty much the changes would be as follows:
- `editable_tree::{Direction, Side}` -> `core/mod.rs`
- `ast::size::Size` -> `core/mod.rs`
- `editable_tree::cursor::Path` -> `core/path.rs` (now `core::path::Path`)
- `edtable_tree::mod.rs` -> `editor/dag.rs` (so DAG moves from `editable_tree::DAG` to `editor::dag::DAG`)
- We should probably re-import `core::path::Path` as `core::Path`, so we'd add `pub use path::Path` to the top of `core/mod.rs`
- Delete any now-empty files/directories

**Comment by kneasle** [comment]
@stokhos, do you want to do this?  I think it needs to be done when there are no other PRs because moving files around creates really painful merge conflicts (definitely #53 and #54 need to be merged).  I'll definitely co-ordinate other PRs around this.

It looks a little bit fiddly, but I think you'd definitely be up to the challenge.

**Comment by stokhos** [comment]
Yes, I can do this.
