### ISSUE TITLE
Rename `DAG` and `JSON` to pascal case

### ISSUE THREAD

**Issue by kneasle** [kneasle/sapling#62]
In the crates.io guidelines, names which are acronyms should still be written as one word (like `Ast` is now).  However, Sapling's code currently has `DAG`, `JSON` and `TestJSON` which should be `Dag`, `Json` and `TestJson` respectively.

**This will likely break any in-progress PRs.  I have one in progress (but not published yet), so please don't do this until I remove this message.** Thanks!

**Comment by kneasle** [comment]
This isn't the most interesting thing to fix, but would be a good way to get a good look of the code-base.

**Comment by stokhos** [comment]
Are you working on this one ? If not I can fix this.

**Comment by kneasle** [comment]
You're welcome to it, **but** I'm working on a big PR that I haven't published yet, and fixing this before my PR is merged will generate a _ton_ of merge conflicts.

I'll publish and possibly merge the big PR tonight, and then it's all yours.

**Comment by stokhos** [comment]
Cool, I will wait, until you merge your PR.

**Comment by kneasle** [comment]
Cool!  PR (#64) has now been merged - this is all yours.
