### ISSUE TITLE
Any other things that I can work on?

### ISSUE THREAD

**Issue by stokhos** [kneasle/sapling#75]

**Comment by kneasle** [comment]
:laughing: love it!  Great enthusiasm.

I think there are a few bugs that I have in my sights for a while that you're welcome to fix if you want.  I'll make them as new issues, and you're welcome to pick which one you want.

Also if you want to get your hands dirty with macros you can do #46, and #13 looks like some fun too.  But I guess you've probably looked through the existing issues...

**Comment by stokhos** [comment]
> Also if you want to get your hands dirty with macros you can do #46, and #13 looks like some fun too. But I guess you've probably looked through the existing issues...

I will try to work on those later this month. Kind of exhausted : /

**Comment by kneasle** [comment]
I'm pretty sure I have more issues that you can do other than #77, but it's 1am for me so I'm off to bed...

> I will try to work on those later this month. Kind of exhausted : /

That's fair - it's completely up to you, I just thought that of the existing issues, they're the most approachable.  You do what you want to do - I don't want you to feel obliged to keep working on Sapling (though I very much appreciate your help).  Do it if you enjoy it.

> I love coding and coding in Rust is like giving my brain a break . Most of my time, I do scientific computing in python, I'm so bored with it

I do like how different Rust is to Python.  I'm currently working on two fairly big projects (this and a Python project called [Wheatley](https://github.com/kneasle/wheatley)), and the lack of a pedantic compiler makes it so easy to accidentally break things.  But Rust is very ill-suited to scientific-style computing - it requires a steep learning curve to get started and the effort only really pays off on large projects where safety and performance are both needed.
