### ISSUE TITLE
Incorrect cursor position after undo

### ISSUE THREAD

**Issue by kneasle** [kneasle/sapling#77]
After undo, the cursor should be returned to where it was just before that change was made.  However, this is not the case - the cursor is moved to its location after the previous edit.

I think the cause of this is that there's some confusion over what the `Path`s in `Dag::root_history` are supposed to signify - in a snapshot `(&'arena Node, Path)`, the `Path` should be what `Dag::current_cursor_path` should be set to when that snapshot is loaded in the undo history, but it's too late at night for me to puzzle this out.
  
  Ideally, we'd store the history as an alternating list of `Path`s and `Root`s (always starting and ending with a `Path`) and then there'd be no ambiguity over what the `Path`s mean.  Such a datatype would be an interesting but hard project with a fair amount of `unsafe`.

This is related to #27.

**Comment by stokhos** [comment]
I‘m working on this one.

**Comment by kneasle** [comment]
Cool! If you want any pointers then just shout, but I don't know where this bug is coming from so I don't know what the solution is.

**Comment by stokhos** [comment]
> After undo, the cursor should be returned to where it was just before that change was made. However, this is not the case - the cursor is moved to its location after the previous edit. 

I'm confused with this line.  Can you give me an example over this? I'm not sure what is the expected behaviour and what is not.

**Comment by kneasle** [comment]
Ah yes I did word that very badly... :laughing:

The issue arises if you move the cursor and then make an edit (which is a very common thing to do).  Suppose that you have the following JSON, and you're selecting the root but want to replace the inner array with `true`:
```json
<[
    true,
    false,
    []
]>
```

To get the cursor to the inner array, we'd type `cjj` (move `Down` then `Next` twice):
```json
[
    true,
    false,
    <[]>
]
```

And now we insert `true` with `rt`:
```json
[
    true,
    false,
    <true>
]
```

Now, if we undo, we'd expect the cursor to stay where it is (because that was where the edit happens), but instead it jumps us back to the root.

I've done some experimentation to make this example, and it looks like this bug only happens with `replace` and `insert_sibling`, but not `insert_child` which might help narrow down the problem.

Also, if you use any debug prints then it'd probably be good to use `log::debug!` and then we can keep the info for future debugging.

**Comment by stokhos** [comment]
Is there a way to move `debug` output to the right side of screen? 
On my pc, I can't see the full `debug` log.
