### ISSUE TITLE
Add way to print sequences of `Key`s to strings

### ISSUE THREAD

**Issue by kneasle** [kneasle/sapling#79]
In a yet-to-be-published PR, I've made `normal_mode` receive `tuikit::Key`s instead of `char`s.  However, there isn't function to convert multiple `Key`s into one string for easy displaying.  We'd probably want a function in `core` to do that.

**Comment by stokhos** [comment]
I'd like to fix this.
where do you want the string to be printed?

**Comment by kneasle** [comment]
The main reason we need this is so that #80 doesn't mess up the readout in the bottom right corner, as seen here:

![image](https://user-images.githubusercontent.com/32932209/104850404-c2de4100-58e6-11eb-9233-a4c042c34bfd.png)

What would be ideal is to have a function which takes a slice of `Key`s and converts them into a string by calling [`core::key_display::KeyDisplay::compact_string`](https://github.com/kneasle/sapling/blob/master/src/core/key_display.rs#L14) on each of them in turn.  We can then use it for the bottom-right-corner readout, and the key stroke list in the [keystroke log](https://github.com/kneasle/sapling/blob/master/src/editor/keystroke_log.rs#L95).

I think it would be tidy to add this function to `KeyDisplay` too.

**Comment by stokhos** [comment]
Can you show me the code bock for the bottom-right-corner readout?

**Comment by kneasle** [comment]
It's [here](https://github.com/kneasle/sapling/blob/master/src/editor/mod.rs#L214) . The rest of the related code should be reachable easily by jumping to definition a load of times.

**Comment by stokhos** [comment]
>I think it would be tidy to add this function to `KeyDisplay` too.

Can you be more specific over this

```rust
pub fn keystrokes_to_string(keystroke_buffer: &Vec<Key>) -> String {
    keystroke_buffer
        .iter()
        .map(|x| x.compact_string())
        .collect()
}
```
This is my implementation, and it won't work with `KeyDisplay`
