### ISSUE TITLE
replace crashes sapling

### ISSUE THREAD

**Issue by stokhos** [kneasle/sapling#83]
For an array of size 3, cursor on 1st node, `4rt` crashes sapling

**Comment by kneasle** [comment]
Oh yes! I'll see if I can fix this in my refactoring - the current replace code is horrible and difficult to maintain, so I'll try and track this down after the refactoring.

**Comment by stokhos** [comment]
Are you still working on this? If not, I'd give this a try

**Comment by kneasle** [comment]
It's all yours!  I think it should be fixable with just a simple bounds check (it feels a bit hacky but the code is in line to be refactored at some point anyway).  Sorry for the slowish reply - it's the last week of term and I had loads of things to get done...

**Comment by stokhos** [comment]
>  Sorry for the slowish reply - it's the last week of term and I had loads of things to get done...

No worries. I'm busy too my midterms are coming :/

**Comment by kneasle** [comment]
I guess midterms are some form of exams?  If so, good luck!  (I'm completely ignorant of the US education system)

**Comment by stokhos** [comment]
> I guess midterms are some form of exams? If so, good luck! (I'm completely ignorant of the US education system)

Yes, it is, in the mid of the semester we usually have an exam.

**Comment by stokhos** [comment]
Do you have a plan on how to do the refactor, maybe I can do the refactor.

**Comment by kneasle** [comment]
> Do you have a plan on how to do the refactor, maybe I can do the refactor.

The refactor in question is a side effect of a rewrite I plan to do of how the `ast` module works, which I started on stream a while back but didn't finish because I couldn't find a good way to make things work (I can't really remember what happened now).

**Comment by stokhos** [comment]
Is there any other things that I can work on?

**Comment by kneasle** [comment]
I'm not sure... I've mostly lost track of what's happening with Sapling since my mind is on other projects at the moment.  Also, the code is in need of some big refactoring anyway, so all the issues right now are either really complicated and critical or small and fairly trivial.  I will eventually get back to working on Sapling at which point there'll suddenly be more interesting things happening and I'll let you know when things are available.
